import { BedDouble, Building, Building2, Home, Layers, Map, Square, Store } from 'lucide-react'

export const TYPE_ORDER = [
  'appartement',
  'villa',
  'duplex',
  'studio',
  'chambre',
  'immeuble',
  'local-commercial',
  'terrain',
]

export const FORM_TYPE_CONFIG = {
  appartement: {
    label: 'Appartement',
    description: 'Logement dans un immeuble collectif',
    icon: Building,
    typeName: 'Appartement',
    titlePlaceholder: 'Ex: Appartement 3 pieces 1 salon 1 douche - Cocody',
    addressPlaceholder: 'Ex: Rue 12, Residence Les Acacias, Cocody',
    fields: { surface: true, chambres: true, salles_de_bain: true, description: true },
    required: { surface: true, chambres: true, salles_de_bain: true },
    numericRules: { surface: 0, chambres: 1, salles_de_bain: 1 },
    equipements: [
      { key: 'nombre_salons', label: 'Nombre de salons', type: 'number', required: true, min: 1 },
      { key: 'nombre_cuisines', label: 'Nombre de cuisines', type: 'number', min: 0, placeholder: '0' },
      { key: 'balcons', label: 'Balcons', type: 'number', min: 0, placeholder: '0' },
      { key: 'parking_places', label: 'Places de parking', type: 'number', min: 0, placeholder: '0', unit: 'places' },
      { key: 'terrasses', label: 'Terrasses', type: 'number', min: 0, placeholder: '0' },
      { key: 'etage', label: 'Etage', type: 'number', min: 0, placeholder: '0' },
      { key: 'ascenseur', label: 'Ascenseur', type: 'checkbox', group: 'Equipements' },
      { key: 'gardien', label: 'Gardien', type: 'checkbox', group: 'Securite' },
      { key: 'meuble', label: 'Meuble', type: 'checkbox', group: 'Commodites' },
      { key: 'climatisation', label: 'Climatisation', type: 'checkbox', group: 'Commodites' },
      { key: 'eau_chaude', label: 'Eau chaude', type: 'checkbox', group: 'Commodites' },
      { key: 'compteur_cie_individuel', label: 'Compteur CIE individuel', type: 'checkbox', group: 'Commodites' },
      { key: 'compteur_sodeci_individuel', label: 'Compteur SODECI individuel', type: 'checkbox', group: 'Commodites' },
    ],
  },
  villa: {
    label: 'Villa',
    description: 'Maison individuelle avec terrain',
    icon: Home,
    typeName: 'Villa',
    titlePlaceholder: 'Ex: Villa 4 chambres piscine jardin - Riviera',
    addressPlaceholder: 'Ex: Rue 12, Residence Les Acacias, Cocody',
    fields: { surface: true, chambres: true, salles_de_bain: true, description: true },
    required: { surface: true, chambres: true, salles_de_bain: true },
    numericRules: { surface: 0, chambres: 1, salles_de_bain: 1 },
    equipements: [
      { key: 'nombre_salons', label: 'Nombre de salons', type: 'number', required: true, min: 1 },
      { key: 'nombre_cuisines', label: 'Nombre de cuisines', type: 'number', required: true, min: 1 },
      { key: 'terrasses', label: 'Terrasses', type: 'number', min: 0, placeholder: '0' },
      { key: 'balcons', label: 'Balcons', type: 'number', min: 0, placeholder: '0' },
      { key: 'garage_places', label: 'Places de garage', type: 'number', min: 0, placeholder: '0', unit: 'places' },
      { key: 'piscine', label: 'Piscine', type: 'checkbox', group: 'Equipements' },
      { key: 'jardin', label: 'Jardin', type: 'checkbox', group: 'Equipements' },
      { key: 'cour', label: 'Cour', type: 'checkbox', group: 'Equipements' },
      { key: 'dependance', label: 'Dependance', type: 'checkbox', group: 'Equipements' },
      { key: 'forage', label: 'Forage', type: 'checkbox', group: 'Equipements' },
      { key: 'surpresseur', label: 'Surpresseur', type: 'checkbox', group: 'Equipements' },
      { key: 'groupe_electrogene', label: 'Groupe electrogene', type: 'checkbox', group: 'Equipements' },
      { key: 'cuisine_equipee', label: 'Cuisine equipee', type: 'checkbox', group: 'Commodites' },
      { key: 'gardien', label: 'Gardien', type: 'checkbox', group: 'Securite' },
      { key: 'cloture', label: 'Cloture', type: 'checkbox', group: 'Securite' },
      { key: 'acces_route', label: 'Acces route', type: 'checkbox', group: 'Equipements' },
    ],
  },
  duplex: {
    label: 'Duplex',
    description: 'Logement sur deux niveaux',
    icon: Layers,
    typeName: 'Duplex',
    titlePlaceholder: 'Ex: Duplex 3 chambres 2 salons - Marcory',
    addressPlaceholder: 'Ex: Rue 12, Residence Les Acacias, Cocody',
    fields: { surface: true, chambres: true, salles_de_bain: true, description: true },
    required: { surface: true, chambres: true, salles_de_bain: true },
    numericRules: { surface: 0, chambres: 1, salles_de_bain: 1 },
    equipements: [
      { key: 'nombre_salons', label: 'Nombre de salons', type: 'number', required: true, min: 1 },
      { key: 'nombre_cuisines', label: 'Nombre de cuisines', type: 'number', required: true, min: 1 },
      { key: 'terrasses', label: 'Terrasses', type: 'number', min: 0, placeholder: '0' },
      { key: 'balcons', label: 'Balcons', type: 'number', min: 0, placeholder: '0' },
      { key: 'parking_places', label: 'Places de parking', type: 'number', min: 0, placeholder: '0', unit: 'places' },
      { key: 'ascenseur', label: 'Ascenseur', type: 'checkbox', group: 'Equipements' },
      { key: 'cour', label: 'Cour', type: 'checkbox', group: 'Equipements' },
      { key: 'dependance', label: 'Dependance', type: 'checkbox', group: 'Equipements' },
      { key: 'forage', label: 'Forage', type: 'checkbox', group: 'Equipements' },
      { key: 'surpresseur', label: 'Surpresseur', type: 'checkbox', group: 'Equipements' },
      { key: 'groupe_electrogene', label: 'Groupe electrogene', type: 'checkbox', group: 'Equipements' },
      { key: 'cuisine_equipee', label: 'Cuisine equipee', type: 'checkbox', group: 'Commodites' },
      { key: 'acces_route', label: 'Acces route', type: 'checkbox', group: 'Equipements' },
    ],
  },
  studio: {
    label: 'Studio',
    description: 'Logement compact tout-en-un',
    icon: Square,
    typeName: 'Studio',
    titlePlaceholder: 'Ex: Studio meuble climatise - Plateau',
    addressPlaceholder: 'Ex: Rue 12, Residence Les Acacias, Cocody',
    fields: { surface: true, chambres: false, salles_de_bain: true, description: true },
    required: { surface: true, salles_de_bain: true },
    numericRules: { surface: 0, salles_de_bain: 1 },
    impliedValues: { chambres: 1 },
    equipements: [
      { key: 'nombre_cuisines', label: 'Nombre de cuisines', type: 'number', min: 0, placeholder: '0' },
      { key: 'etage', label: 'Etage', type: 'number', min: 0, placeholder: '0' },
      { key: 'parking_places', label: 'Places de parking', type: 'number', min: 0, placeholder: '0', unit: 'places' },
      { key: 'climatisation', label: 'Climatisation', type: 'checkbox', group: 'Commodites' },
      { key: 'meuble', label: 'Meuble', type: 'checkbox', group: 'Commodites' },
      { key: 'eau_chaude', label: 'Eau chaude', type: 'checkbox', group: 'Commodites' },
      { key: 'compteur_cie_individuel', label: 'Compteur CIE individuel', type: 'checkbox', group: 'Commodites' },
      { key: 'compteur_sodeci_individuel', label: 'Compteur SODECI individuel', type: 'checkbox', group: 'Commodites' },
    ],
  },
  chambre: {
    label: 'Chambre',
    description: 'Chambre meublée ou non',
    icon: BedDouble,
    typeName: 'Chambre',
    titlePlaceholder: 'Ex: Chambre meublee salle de bain privee - Yopougon',
    addressPlaceholder: 'Ex: Rue 12, Residence Les Acacias, Cocody',
    fields: { surface: true, chambres: false, salles_de_bain: true, description: true },
    required: { surface: false, salles_de_bain: false },
    numericRules: { surface: 0, salles_de_bain: 0 },
    equipements: [
      { key: 'meublee', label: 'Meublee', type: 'checkbox', group: 'Commodites' },
      { key: 'salle_de_bain_privee', label: 'Salle de bain privee', type: 'checkbox', group: 'Commodites' },
      { key: 'climatisation', label: 'Climatisation', type: 'checkbox', group: 'Commodites' },
      { key: 'eau_chaude', label: 'Eau chaude', type: 'checkbox', group: 'Commodites' },
      { key: 'acces_cuisine', label: 'Acces cuisine', type: 'checkbox', group: 'Commodites' },
      { key: 'compteur_cie_individuel', label: 'Compteur CIE individuel', type: 'checkbox', group: 'Commodites' },
      { key: 'compteur_sodeci_individuel', label: 'Compteur SODECI individuel', type: 'checkbox', group: 'Commodites' },
    ],
  },
  immeuble: {
    label: 'Immeuble',
    description: 'Immeuble entier à vendre ou louer',
    icon: Building2,
    typeName: 'Immeuble',
    titlePlaceholder: 'Ex: Immeuble R+3 12 appartements - Adjame',
    addressPlaceholder: 'Ex: Rue 12, Residence Les Acacias, Cocody',
    fields: { surface: true, chambres: false, salles_de_bain: false, description: true },
    required: { surface: true },
    numericRules: { surface: 0 },
    equipements: [
      { key: 'nombre_etages', label: "Nombre d'etages", type: 'number', required: true, min: 1 },
      { key: 'nombre_lots', label: 'Nombre de lots', type: 'number', min: 0, placeholder: '0' },
      { key: 'nombre_appartements', label: "Nombre d'appartements", type: 'number', min: 0, placeholder: '0' },
      { key: 'nombre_magasins', label: 'Nombre de magasins', type: 'number', min: 0, placeholder: '0' },
      { key: 'parking_places', label: 'Places de parking', type: 'number', min: 0, placeholder: '0', unit: 'places' },
      { key: 'revenu_mensuel_estime', label: 'Revenu mensuel estime', type: 'number', min: 0, placeholder: '0', unit: 'FCFA' },
      { key: 'ascenseur', label: 'Ascenseur', type: 'checkbox', group: 'Equipements' },
      { key: 'gardien', label: 'Gardien', type: 'checkbox', group: 'Securite' },
      { key: 'cour', label: 'Cour', type: 'checkbox', group: 'Equipements' },
      { key: 'titre_foncier', label: 'Titre foncier', type: 'checkbox', group: 'Securite' },
    ],
  },
  'local-commercial': {
    label: 'Local commercial',
    description: 'Bureau, boutique, entrepôt',
    icon: Store,
    typeName: 'Local commercial',
    titlePlaceholder: 'Ex: Local commercial 80m² bord route - Treichville',
    addressPlaceholder: 'Ex: Rue 12, Residence Les Acacias, Cocody',
    fields: { surface: true, chambres: false, salles_de_bain: false, description: true },
    required: { surface: true },
    numericRules: { surface: 0 },
    equipements: [
      { key: 'hauteur_sous_plafond', label: 'Hauteur sous plafond', type: 'number', min: 0, placeholder: '0', unit: 'metres' },
      { key: 'parking_places', label: 'Places de parking', type: 'number', min: 0, placeholder: '0', unit: 'places' },
      {
        key: 'type_activite_autorisee',
        label: 'Type activite autorisee',
        type: 'text',
        placeholder: 'Ex: Boutique, Restaurant, Bureau...',
      },
      { key: 'bord_route', label: 'Bord route', type: 'checkbox', group: 'Equipements' },
      { key: 'zone_passante', label: 'Zone passante', type: 'checkbox', group: 'Equipements' },
      { key: 'rideau_metallique', label: 'Rideau metallique', type: 'checkbox', group: 'Equipements' },
      { key: 'reserve', label: 'Reserve', type: 'checkbox', group: 'Equipements' },
      { key: 'acces_livraison', label: 'Acces livraison', type: 'checkbox', group: 'Equipements' },
      { key: 'climatisation', label: 'Climatisation', type: 'checkbox', group: 'Commodites' },
      { key: 'vitrine', label: 'Vitrine', type: 'checkbox', group: 'Equipements' },
      { key: 'wc', label: 'WC', type: 'checkbox', group: 'Commodites' },
    ],
  },
  terrain: {
    label: 'Terrain',
    description: 'Terrain nu constructible ou agricole',
    icon: Map,
    typeName: 'Terrain',
    titlePlaceholder: 'Ex: Terrain 500m² ACD viabilise - Bingerville',
    addressPlaceholder: 'Ex: Rue 12, Residence Les Acacias, Cocody',
    fields: { surface: true, chambres: false, salles_de_bain: false, description: true },
    required: { surface: true },
    numericRules: { surface: 0 },
    equipements: [
      {
        key: 'document_foncier',
        label: 'Document foncier',
        type: 'select',
        required: true,
        options: [
          { value: 'ACD', label: 'ACD' },
          { value: 'Titre foncier', label: 'Titre foncier' },
          { value: 'Certificat foncier', label: 'Certificat foncier' },
          { value: 'Attestation villageoise', label: 'Attestation villageoise' },
          { value: "Lettre d'attribution", label: "Lettre d'attribution" },
          { value: 'Aucun', label: 'Aucun' },
          { value: 'A verifier', label: 'A verifier' },
        ],
      },
      {
        key: 'type_sol',
        label: 'Type de sol',
        type: 'select',
        options: [
          { value: 'Plat', label: 'Plat' },
          { value: 'En pente', label: 'En pente' },
          { value: 'Remblaye', label: 'Remblaye' },
          { value: 'Marecageux', label: 'Marecageux' },
          { value: 'Argileux', label: 'Argileux' },
          { value: 'Sableux', label: 'Sableux' },
          { value: 'A verifier', label: 'A verifier' },
        ],
      },
      { key: 'lotissement', label: 'Lotissement', type: 'checkbox', group: 'Equipements' },
      { key: 'zone_approuvee', label: 'Zone approuvee', type: 'checkbox', group: 'Equipements' },
      { key: 'eau_disponible', label: 'Eau disponible', type: 'checkbox', group: 'Commodites' },
      { key: 'electricite_disponible', label: 'Electricite disponible', type: 'checkbox', group: 'Commodites' },
      { key: 'bord_route', label: 'Bord route', type: 'checkbox', group: 'Equipements' },
      { key: 'terrain_angle', label: 'Terrain angle', type: 'checkbox', group: 'Equipements' },
      { key: 'acces_route', label: 'Acces route', type: 'checkbox', group: 'Equipements' },
      { key: 'viabilise', label: 'Viabilise', type: 'checkbox', group: 'Equipements' },
      { key: 'cloture', label: 'Cloture', type: 'checkbox', group: 'Securite' },
    ],
  },
}

export const TRANSACTION_OPTIONS = [
  { value: 'louer', label: 'Louer' },
  { value: 'vendre', label: 'Vendre' },
  { value: 'bail', label: 'Bail' },
]
